'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowDownLeft,ArrowUpRight,ArrowRight,Check,ChevronRight,Plus,ShieldCheck,Wallet} from 'lucide-react';
import {naira,compact,fmtDateShort} from '@/lib/format';
import {useSession} from '@/components/shell/session';
import {useCommand} from '@/components/command/CommandContext';
import {scenarioNow} from '@/lib/clock';
type Stats={available_balance:number;received_month:number;spent_month:number;pending_amount:number;pending_approvals:number;transactions_count:number};
type Txn={id:string;counterparty:string;amount:number;direction:string;status:string;category:string;initiated_at:string};
type Approval={payment_id:string;beneficiary_name:string;amount:number;purpose:string;outstanding:string[]};
export default function DashboardPage(){
 const {user}=useSession(); const {openBar,openFlow,runCommand}=useCommand();
 const [stats,setStats]=useState<Stats|null>(null);const [transactions,setTransactions]=useState<Txn[]>([]);const [approvals,setApprovals]=useState<Approval[]>([]);const [error,setError]=useState(false);const [range,setRange]=useState<'month'|'week'>('month');
 useEffect(()=>{let alive=true;async function load(){try{const [s,t,a]=await Promise.all(['/api/stats','/api/transactions?limit=400','/api/approvals'].map(async url=>{const res=await fetch(url);if(!res.ok)throw new Error('offline');return res.json();}));if(!alive)return;setStats(s.stats);setTransactions(t.transactions);setApprovals(a.pending);setError(false);}catch{if(alive)setError(true);}}void load();const timer=setInterval(load,5000);return()=>{alive=false;clearInterval(timer);};},[user?.id]);
 const days=range==='week'?7:29;const end=scenarioNow();const values=Array.from({length:days},(_,i)=>{const date=new Date(end);date.setUTCDate(end.getUTCDate()-days+i+1);const key=date.toISOString().slice(0,10);const rows=transactions.filter(t=>t.initiated_at.startsWith(key)&&t.status==='SUCCESSFUL');return{label:date.getUTCDate(),income:rows.filter(t=>t.direction==='IN').reduce((s,t)=>s+t.amount,0),out:rows.filter(t=>t.direction==='OUT').reduce((s,t)=>s+t.amount,0)};});
 const max=Math.max(...values.flatMap(v=>[v.income,v.out]),1);const points=(key:'income'|'out')=>values.map((v,i)=>`${i*600/Math.max(days-1,1)},${170-v[key]/max*140}`).join(' ');
 return <div className="dashboard-wrap"><div className="flex flex-wrap gap-4 justify-between items-end mb-7"><div><p className="kicker mb-2">YOUR FINANCIAL WORKSPACE</p><h1 className="text-[29px] sm:text-[35px] font-semibold tracking-tight">A clear view. A confident move.</h1><p className="text-sm text-ink2 mt-2">Good afternoon, {user?.first_name}. Hereâ€™s where your business stands.</p></div><span className="text-xs text-ink2 border border-line rounded-lg px-3 py-2">29 September 2026 Â· Demo date</span></div>{error&&<div role="alert" className="mb-4 rounded-xl bg-warn/10 text-warn p-3 text-sm">Connection interrupted. Showing the last available information.</div>}
 <div className="grid grid-cols-1 xl:grid-cols-[1.6fr_1fr] gap-5"><section className="balance-hero"><div className="flex justify-between items-center"><span className="text-xs text-white/70 flex items-center gap-2"><Wallet size={16}/> Available balance</span><span className="text-[10px] rounded-full border border-white/20 px-2.5 py-1">NGN ACCOUNT</span></div><div className="text-[clamp(28px,4.1vw,48px)] tracking-tight font-medium mt-6 num break-words">{stats?naira(stats.available_balance):'Loadingâ€¦'}</div><p className="text-xs text-white/60 mt-2">Operating account Â· Zytrex Payments</p><div className="flex flex-wrap gap-3 mt-7"><button className="btn bg-[#9cedd8] text-[#153b37] hover:bg-[#b5f5e5]" onClick={()=>openBar('Pay ')}><Plus size={15}/> Make a payment</button><Link className="btn border-white/25 text-white hover:bg-white/10" href="/transactions">View transactions <ArrowUpRight size={14}/></Link></div><div className="hero-orbit" aria-hidden="true"/></section><section className="card p-6 flex flex-col justify-between"><div className="flex justify-between"><span className="kicker">CONTROL, BUILT IN</span><ShieldCheck size={21} className="text-accent"/></div><div className="my-4"><h2 className="text-xl font-medium tracking-tight">Your next move,<br/>one command away.</h2><p className="text-xs text-ink2 leading-relaxed mt-2 max-w-[270px]">Find a payment, understand your spending, or prepare a transfer. You stay in control.</p></div><button className="flex items-center justify-between w-full border-t border-line pt-4 text-sm font-medium text-accent" onClick={()=>openBar()}>What would you like to do? <ArrowRight size={16}/></button></section></div>
 <div className="grid grid-cols-1 sm:grid-cols-3 gap-0 sm:gap-6 border-y border-line my-7 py-2 sm:py-5">{[{label:'Money in',amount:stats?.received_month,icon:ArrowDownLeft,note:'Received this month',color:'text-success'},{label:'Money out',amount:stats?.spent_month,icon:ArrowUpRight,note:'Paid this month',color:'text-ink'},{label:'Awaiting approval',amount:stats?.pending_amount,icon:ShieldCheck,note:`${stats?.pending_approvals??'â€”'} payment requests`,color:'text-warn'}].map((m,i)=><div className={`py-3 sm:py-0 ${i?'sm:border-l sm:pl-6 border-line':''}`} key={m.label}><div className="flex items-center gap-2 text-xs text-ink2"><m.icon size={15} className={m.color}/>{m.label}</div><div className="text-[25px] font-medium tracking-tight mt-2 num">{m.amount==null?'â€”':compact(m.amount)}</div><div className="text-[11px] text-ink2 mt-1">{m.note}</div></div>)}</div>
 <div className="grid grid-cols-1 xl:grid-cols-[1.6fr_1fr] gap-5"><section className="card p-5 sm:p-6"><div className="flex flex-wrap justify-between items-center gap-3"><div><h2 className="font-semibold text-[15px]">Cash flow</h2><p className="text-xs text-ink2 mt-1">Know whatâ€™s coming in. Plan what goes out.</p></div><select aria-label="Cash flow period" className="rounded-lg border border-line px-2 py-2 text-xs bg-panel" value={range} onChange={e=>setRange(e.target.value as 'month'|'week')}><option value="month">This month</option><option value="week">Last 7 days</option></select></div><div className="flex gap-4 text-[11px] mt-5"><span className="flex gap-2 items-center"><i className="w-2 h-2 rounded-full bg-[#13a995]"/>Money in</span><span className="flex gap-2 items-center"><i className="w-2 h-2 rounded-full bg-[#233f51]"/>Money out</span><span className="ml-auto text-ink2">Daily Â· NGN</span></div><svg viewBox="0 0 600 200" className="w-full mt-4" role="img" aria-label="Daily incoming and outgoing sandbox payments for September 2026"><defs><linearGradient id="cashfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#13a995" stopOpacity="0.15"/><stop offset="100%" stopColor="#13a995" stopOpacity="0"/></linearGradient></defs>{[30,76,123,170].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="#e7eeee" strokeDasharray="4 5"/>)}<polygon points={`0,170 ${points('income')} 600,170`} fill="url(#cashfill)"/><polyline points={points('income')} fill="none" stroke="#13a995" strokeWidth="2.5" strokeLinejoin="round"/><polyline points={points('out')} fill="none" stroke="#233f51" strokeWidth="2" strokeLinejoin="round"/>{values.filter((_,i)=>i===0||i===days-1||i%7===0).map(v=><text key={v.label} x={values.indexOf(v)*600/Math.max(days-1,1)} y="196" textAnchor={v===values[0]?'start':v===values[days-1]?'end':'middle'} fontSize="10" fill="#637780">Sep {v.label}</text>)}</svg><button onClick={()=>void runCommand('How much did we spend this month?')} className="text-xs font-medium text-accent flex gap-2 items-center mt-4">Explore spending breakdown <ArrowUpRight size={13}/></button></section>
 <section className="card p-5 sm:p-6"><div className="flex justify-between items-center"><h2 className="font-semibold text-[15px]">Needs attention</h2><span className="badge bg-warn/10 text-warn">{approvals.length} pending</span></div><p className="text-xs text-ink2 mt-1 mb-4">Keep business moving, with the right checks.</p><div className="divide-y divide-line">{approvals.slice(0,3).map(a=><button key={a.payment_id} onClick={()=>openFlow({paymentId:a.payment_id})} className="w-full text-left flex gap-3 items-center py-4 group"><span className="w-9 h-9 shrink-0 rounded-xl bg-[#edf3f2] grid place-items-center text-xs font-semibold text-accent">{a.beneficiary_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{a.beneficiary_name}</span><span className="block truncate text-[10px] text-ink2 mt-1">{a.outstanding.join(' + ')} approval</span></div><span className="text-xs font-medium whitespace-nowrap">{compact(a.amount)}</span><ChevronRight size={13} className="text-ink3"/></button>)}{!approvals.length&&<p className="py-7 text-sm text-ink2 flex gap-2"><Check size={16}/> Nothing waiting for approval.</p>}</div><Link href="/approvals" className="text-xs text-accent font-medium inline-flex gap-2 items-center mt-3">View all approvals <ArrowRight size={13}/></Link></section></div>
 <section className="card mt-5 overflow-hidden"><div className="px-5 sm:px-6 py-5 flex justify-between items-center"><div><h2 className="font-semibold text-[15px]">Recent activity</h2><p className="text-xs text-ink2 mt-1">A record of every move.</p></div><Link href="/transactions" className="text-xs text-accent font-medium">View all â†—</Link></div><div className="activity-head"><span>Transaction</span><span>Category</span><span>Date</span><span className="text-right">Amount</span></div>{transactions.slice(0,5).map(t=><Link href="/transactions" key={t.id} className="activity-row"><span className="flex items-center gap-3 min-w-0"><span className="w-9 h-9 shrink-0 rounded-full bg-panel2 grid place-items-center">{t.direction==='IN'?<ArrowDownLeft size={16} className="text-success"/>:<ArrowUpRight size={16}/>}</span><span className="min-w-0"><span className="block truncate text-xs font-medium">{t.counterparty}</span><span className={`block text-[10px] mt-1 ${t.status==='FAILED'?'text-danger':'text-ink2'}`}>{t.status==='FAILED'?'Failed':'Completed'}</span></span></span><span className="hidden md:block text-xs text-ink2">{t.category}</span><span className="hidden md:block text-xs text-ink2">{fmtDateShort(t.initiated_at)}</span><span className={`text-right text-xs sm:text-sm font-medium num whitespace-nowrap ${t.direction==='IN'?'text-success':''}`}>{t.direction==='IN'?'+':'âˆ’'}{naira(t.amount)}</span></Link>)}{!transactions.length&&<p className="p-6 text-sm text-ink2">{stats?'No recent transactions.':'Loading activityâ€¦'}</p>}</section><p className="text-[10px] text-ink2 mt-5 flex items-center gap-2"><ShieldCheck size={12}/> Simulated balances and payments. No real money moves.</p></div>;
}
