'use client';

// The generated interface — results appear as a focused surface on the right,
// never as a chat transcript. One insight sentence + the structured data.

import { useDialog } from '@/components/ui/useDialog';
import { useRouter } from 'next/navigation';
import { ArrowRight, X } from 'lucide-react';
import type { ChatCard } from '@/lib/types';
import { ROLE_LABELS } from '@/lib/types';
import { fmtDateShort, naira, naira0, pct } from '@/lib/format';
import { StatusBadge } from '@/components/ui/badge';
import { useCommand } from './CommandContext';

export interface SurfaceData {
  text: string;
  cards?: ChatCard[];
  tool?: { name: string; ms?: number; summary?: string };
}

export function ResultSurface({ data, onClose }: { data: SurfaceData; onClose: () => void }) {
  const dialogRef = useDialog(true, onClose);
  const router = useRouter();
  const { openFlow } = useCommand();

  return (
    <>
      <div className="fixed inset-0 z-40 bg-black/20 anim-fade-in" onClick={onClose} />
      <div ref={dialogRef} role="dialog" aria-modal="true" aria-label="Command result" tabIndex={-1} className="fixed right-0 top-0 bottom-0 z-50 w-full sm:w-[460px] sheet anim-sheet-in flex flex-col">
        {/* header */}
        <header className="flex items-start justify-between gap-3 px-5 pt-5 pb-4 border-b border-line">
          <div className="min-w-0">
            {data.tool && (
              <div className="flex items-center gap-2 mb-1.5">
                <span className="w-4.5 h-4.5 min-w-4 rounded bg-accent text-white grid place-items-center text-[9px] font-bold leading-none" style={{ width: 18, height: 18 }}>Z</span>
                <span className="mono text-[10.5px] text-ink3 truncate">
                  Zytrex insight
                </span>
              </div>
            )}
            <p className="text-[13.5px] leading-relaxed text-ink2">{data.text}</p>
          </div>
          <button className="btn btn-ghost btn-sm !px-2 shrink-0" onClick={onClose} aria-label="Close">
            <X size={16} />
          </button>
        </header>

        {/* generated content */}
        <div className="flex-1 overflow-y-auto px-5 py-5 space-y-4 stagger">
          {data.cards?.map((card, i) => (
            <CardView
              key={i}
              card={card}
              onNavigate={(to) => { onClose(); router.push(to); }}
              onFlow={(paymentId) => { onClose(); openFlow({ paymentId }); }}
              onPrepare={(preview) => { onClose(); openFlow({ preview, initial: 'preview' }); }}
            />
          ))}
          {!data.cards?.length && (
            <div className="card p-5 text-[13px] text-ink2">
              Nothing to display — try a command like “Pay Godwin Engineering ₦520k for LASCON” or “Show failed transactions this month”.
            </div>
          )}
        </div>

        <footer className="border-t border-line px-5 py-3 text-[10.5px] text-ink3 text-center tracking-wide">
          SANDBOX · generated by Zytrex command
        </footer>
      </div>
    </>
  );
}

function CardView({
  card,
  onNavigate,
  onFlow,
  onPrepare,
}: {
  card: ChatCard;
  onNavigate: (to: string) => void;
  onFlow: (paymentId: string) => void;
  onPrepare: (preview: Extract<ChatCard, { kind: 'transfer_preview' }>) => void;
}) {
  switch (card.kind) {
    case 'balance':
      return (
        <section className="card overflow-hidden">
          <div className="px-5 pt-4 pb-3">
            <div className="kicker">Available balance</div>
            <div className="mono text-[32px] font-bold tracking-tight mt-1 num">{naira(card.available)}</div>
            <div className="text-[12px] text-ink3 mt-0.5 mono">Ledger {naira(card.ledger)}</div>
          </div>
          <div className="border-t border-line divide-y divide-line">
            {card.accounts.map((a) => (
              <div key={a.mask} className="flex items-center justify-between px-5 py-2.5 text-[13px]">
                <span className="text-ink2">{a.label} <span className="mono text-ink3">••••{a.mask}</span></span>
                <span className="mono font-medium">{naira(a.balance)}</span>
              </div>
            ))}
          </div>
        </section>
      );

    case 'spending': {
      const max = Math.max(...card.categories.map((c) => c.total), 1);
      return (
        <section className="card p-5">
          <div className="kicker">{card.period} spending</div>
          <div className="flex items-end gap-3 mt-1">
            <div className="mono text-[32px] font-bold tracking-tight num">{naira(card.total)}</div>
            {card.change_pct != null && (
              <span className={`mb-1.5 text-[12.5px] font-semibold ${card.change_pct >= 0 ? 'text-danger' : 'text-success'}`}>
                {card.change_pct >= 0 ? '↑' : '↓'} {pct(Math.abs(card.change_pct))} {card.change_label ?? 'vs last period'}
              </span>
            )}
          </div>
          <div className="text-[12px] text-ink3 mb-4">{card.count} transactions</div>
          <div className="space-y-3">
            {card.categories.map((c) => (
              <div key={c.name}>
                <div className="flex justify-between text-[13px] mb-1">
                  <span className="text-ink2">{c.name}</span>
                  <span className="mono font-medium">{naira0(c.total)}</span>
                </div>
                <div className="h-1.5 rounded-full bg-panel2 overflow-hidden">
                  <div className="h-full rounded-full bg-accent" style={{ width: `${Math.round((c.total / max) * 100)}%` }} />
                </div>
              </div>
            ))}
          </div>
        </section>
      );
    }

    case 'compare': {
      const diff = card.b.total - card.a.total;
      return (
        <section className="card p-5">
          <div className="kicker">Period comparison</div>
          <div className="grid grid-cols-2 gap-4 mt-3">
            <div>
              <div className="text-[12px] text-ink3">{card.a.label}</div>
              <div className="mono text-[20px] font-semibold mt-0.5">{naira0(card.a.total)}</div>
            </div>
            <div>
              <div className="text-[12px] text-ink3">{card.b.label}</div>
              <div className="mono text-[20px] font-semibold mt-0.5">{naira0(card.b.total)}</div>
            </div>
          </div>
          <div className="mt-4 pt-3 border-t border-line flex items-center justify-between">
            <span className={`text-[14px] font-semibold ${card.change_pct >= 0 ? 'text-danger' : 'text-success'}`}>
              {card.change_pct >= 0 ? '↑' : '↓'} {pct(Math.abs(card.change_pct))}
            </span>
            <span className="text-[12.5px] text-ink2 mono">
              {diff >= 0 ? '+' : '−'}{naira0(Math.abs(diff))}
            </span>
          </div>
        </section>
      );
    }

    case 'transactions':
      return (
        <section className="card overflow-hidden">
          <div className="flex items-center justify-between px-4 pt-4 pb-2">
            <div>
              <div className="kicker">{card.title}</div>
              <div className="mono text-[22px] font-bold mt-1">{naira0(card.total)}</div>
              <div className="text-[12px] text-ink3">{card.count} transactions</div>
            </div>
          </div>
          <div className="divide-y divide-line border-t border-line">
            {card.rows.map((t) => (
              <div key={t.id} className="flex items-center gap-3 px-4 py-2.5">
                <div className="min-w-0 flex-1">
                  <div className="text-[13px] font-medium truncate">{t.counterparty}</div>
                  <div className="text-[11.5px] text-ink3 truncate">{fmtDateShort(t.date)} · {t.category}</div>
                </div>
                <div className="text-right">
                  <div className={`mono text-[13px] font-semibold ${t.direction === 'IN' ? 'text-success' : ''}`}>
                    {t.direction === 'IN' ? '+' : '−'}{naira(t.amount)}
                  </div>
                  <StatusBadge status={t.status} />
                </div>
              </div>
            ))}
          </div>
          {card.link && (
            <button className="w-full flex items-center justify-center gap-1.5 py-3 border-t border-line text-[13px] font-semibold text-accent hover:bg-panel2 transition"
              onClick={() => onNavigate(card.link!)}>
              View all <ArrowRight size={14} />
            </button>
          )}
        </section>
      );

    case 'vendors': {
      const max = Math.max(...card.rows.map((r) => r.total), 1);
      return (
        <section className="card p-5">
          <div className="kicker">Top vendors · {card.period}</div>
          <div className="space-y-3.5 mt-3">
            {card.rows.map((r, i) => (
              <div key={r.name}>
                <div className="flex justify-between text-[13px] mb-1">
                  <span className="font-medium"><span className="text-ink3 mono mr-1.5">{i + 1}</span>{r.name}</span>
                  <span className="mono">{naira0(r.total)} <span className="text-ink3">· {r.count}</span></span>
                </div>
                <div className="h-1.5 rounded-full bg-panel2 overflow-hidden">
                  <div className="h-full rounded-full bg-accent" style={{ width: `${Math.round((r.total / max) * 100)}%` }} />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-4 pt-3 border-t border-line flex justify-between text-[13px]">
            <span className="text-ink2">Total</span>
            <span className="mono font-semibold">{naira(card.total)}</span>
          </div>
        </section>
      );
    }

    case 'beneficiary_history':
      return (
        <section className="card overflow-hidden">
          <div className="px-5 pt-4 pb-3">
            <div className="flex items-center justify-between">
              <div className="kicker">Payments</div>
              <StatusBadge status={card.verified === 'VERIFIED' ? 'SUCCESSFUL' : 'PENDING'} />
            </div>
            <div className="text-[15px] font-semibold mt-1">{card.beneficiary_name}</div>
            <div className="text-[12px] text-ink3">{card.bank_name} ••••{card.account_mask}</div>
            <div className="flex items-end gap-6 mt-3">
              <div>
                <div className="mono text-[26px] font-bold">{naira0(card.total)}</div>
                <div className="text-[11.5px] text-ink3">Total paid</div>
              </div>
              <div>
                <div className="mono text-[26px] font-bold">{card.count}</div>
                <div className="text-[11.5px] text-ink3">Transactions</div>
              </div>
            </div>
          </div>
          <div className="divide-y divide-line border-t border-line">
            {card.rows.map((r) => (
              <div key={r.id} className="flex items-center justify-between px-5 py-2.5">
                <div className="min-w-0">
                  <div className="text-[13px] truncate">{r.description}</div>
                  <div className="text-[11.5px] text-ink3 mono">{fmtDateShort(r.date)} · {r.ref}</div>
                </div>
                <span className="mono text-[13.5px] font-semibold">{naira(r.amount)}</span>
              </div>
            ))}
          </div>
        </section>
      );

    case 'approvals':
      return (
        <section className="card overflow-hidden">
          <div className="px-5 pt-4 pb-2 flex items-center justify-between">
            <div className="kicker">Pending approvals</div>
            <span className="badge bg-warn/10 text-warn border border-warn/30">{card.rows.length}</span>
          </div>
          <div className="divide-y divide-line border-t border-line">
            {card.rows.map((r) => (
              <div key={r.payment_id} className="flex items-center justify-between px-5 py-3">
                <div className="min-w-0">
                  <div className="text-[13px] font-medium truncate">{r.beneficiary_name}</div>
                  <div className="text-[11.5px] text-ink3 truncate">{r.ref} · {r.purpose}</div>
                </div>
                <div className="text-right">
                  <div className="mono text-[13.5px] font-semibold">{naira0(r.amount)}</div>
                  <div className="text-[11px] text-ink3">needs {r.outstanding.map((o) => ROLE_LABELS[o]).join(' + ') || '—'}</div>
                </div>
              </div>
            ))}
            {!card.rows.length && <div className="px-5 py-4 text-[13px] text-ink3">All clear — nothing waiting.</div>}
          </div>
          <button className="w-full flex items-center justify-center gap-1.5 py-3 border-t border-line text-[13px] font-semibold text-accent hover:bg-panel2 transition"
            onClick={() => onNavigate('/approvals')}>
            Open approvals <ArrowRight size={14} />
          </button>
        </section>
      );

    case 'info':
      return (
        <section className="card p-5">
          <div className="kicker">{card.title}</div>
          <ul className="mt-2 space-y-1.5 text-[13.5px] text-ink2 leading-relaxed">
            {card.lines.map((l, i) => (
              <li key={i}>{l}</li>
            ))}
          </ul>
        </section>
      );

    case 'payment':
      return (
        <section className="card p-5">
          <div className="flex items-center justify-between">
            <div className="kicker">Payment {card.ref}</div>
            <StatusBadge status={card.status} />
          </div>
          <div className="mono text-[26px] font-bold mt-1.5">{naira(card.amount)}</div>
          <div className="text-[13.5px] font-medium">{card.beneficiary_name}</div>
          <div className="text-[12.5px] text-ink3">{card.bank_name} ••••{card.account_mask} · {card.purpose}</div>
          <button className="btn btn-secondary btn-sm w-full mt-4" onClick={() => onFlow(card.payment_id)}>
            Open payment <ArrowRight size={14} />
          </button>
        </section>
      );

    case 'transfer_preview':
      return (
        <section className="card p-5 border-accent/40">
          <div className="kicker text-accent">Payment</div>
          <div className="mono text-[30px] font-bold tracking-tight mt-1">{naira(card.amount)}</div>
          <div className="text-[14px] font-semibold mt-1">{card.beneficiary.name}</div>
          <div className="text-[12.5px] text-ink3">{card.beneficiary.bank_name} ••••{card.beneficiary.account_mask}</div>
          <div className="text-[12.5px] text-ink2 mt-1.5">{card.purpose}</div>
          <button className="btn btn-primary w-full mt-4" onClick={() => onPrepare(card)}>
            Continue <ArrowRight size={15} />
          </button>
        </section>
      );

    default:
      return null;
  }
}
